//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMCrud {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MVVMCrud.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string action_refresh {
            get {
                return ResourceManager.GetString("action_refresh", resourceCulture);
            }
        }
        
        internal static string list_loading_more {
            get {
                return ResourceManager.GetString("list_loading_more", resourceCulture);
            }
        }
        
        internal static string msg_confirm_upload {
            get {
                return ResourceManager.GetString("msg_confirm_upload", resourceCulture);
            }
        }
        
        internal static string msg_confirm_delete {
            get {
                return ResourceManager.GetString("msg_confirm_delete", resourceCulture);
            }
        }
        
        internal static string msg_empty_list {
            get {
                return ResourceManager.GetString("msg_empty_list", resourceCulture);
            }
        }
        
        internal static string msg_loading {
            get {
                return ResourceManager.GetString("msg_loading", resourceCulture);
            }
        }
        
        internal static string error_data_loading {
            get {
                return ResourceManager.GetString("error_data_loading", resourceCulture);
            }
        }
        
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        internal static string placeholder_search {
            get {
                return ResourceManager.GetString("placeholder_search", resourceCulture);
            }
        }
        
        internal static string msg_search_not_result_found {
            get {
                return ResourceManager.GetString("msg_search_not_result_found", resourceCulture);
            }
        }
        
        internal static string error_internet_connection {
            get {
                return ResourceManager.GetString("error_internet_connection", resourceCulture);
            }
        }
        
        internal static string error_generic {
            get {
                return ResourceManager.GetString("error_generic", resourceCulture);
            }
        }
        
        internal static string action_yes {
            get {
                return ResourceManager.GetString("action_yes", resourceCulture);
            }
        }
        
        internal static string action_no {
            get {
                return ResourceManager.GetString("action_no", resourceCulture);
            }
        }
        
        internal static string item_added_successfully {
            get {
                return ResourceManager.GetString("item_added_successfully", resourceCulture);
            }
        }
        
        internal static string item_update_successfully {
            get {
                return ResourceManager.GetString("item_update_successfully", resourceCulture);
            }
        }
        
        internal static string item_deleted_successfully {
            get {
                return ResourceManager.GetString("item_deleted_successfully", resourceCulture);
            }
        }
    }
}
