//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMCrud {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_it {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_it() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVVMCrud.AppResources.it", typeof(AppResources_it).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi.
        /// </summary>
        internal static string action_add {
            get {
                return ResourceManager.GetString("action_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string action_no {
            get {
                return ResourceManager.GetString("action_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica.
        /// </summary>
        internal static string action_options {
            get {
                return ResourceManager.GetString("action_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ricarica.
        /// </summary>
        internal static string action_refresh {
            get {
                return ResourceManager.GetString("action_refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invia.
        /// </summary>
        internal static string action_send {
            get {
                return ResourceManager.GetString("action_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        internal static string action_yes {
            get {
                return ResourceManager.GetString("action_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulla.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore Interno.
        /// </summary>
        internal static string error_data_loading {
            get {
                return ResourceManager.GetString("error_data_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi dispiace, si è verificato un problema! Controlla la presenza di connessione e riprova in seguito!.
        /// </summary>
        internal static string error_generic {
            get {
                return ResourceManager.GetString("error_generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessuna connessione.
        /// </summary>
        internal static string error_internet_connection {
            get {
                return ResourceManager.GetString("error_internet_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caricato..
        /// </summary>
        internal static string item_added_successfully {
            get {
                return ResourceManager.GetString("item_added_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellato..
        /// </summary>
        internal static string item_deleted_successfully {
            get {
                return ResourceManager.GetString("item_deleted_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificato..
        /// </summary>
        internal static string item_update_successfully {
            get {
                return ResourceManager.GetString("item_update_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostra Altro.
        /// </summary>
        internal static string list_loading_more {
            get {
                return ResourceManager.GetString("list_loading_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confermi di voler cancellare?.
        /// </summary>
        internal static string msg_confirm_delete {
            get {
                return ResourceManager.GetString("msg_confirm_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confermi di voler caricare questi dati?.
        /// </summary>
        internal static string msg_confirm_upload {
            get {
                return ResourceManager.GetString("msg_confirm_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessun dato.
        /// </summary>
        internal static string msg_empty_list {
            get {
                return ResourceManager.GetString("msg_empty_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendi....
        /// </summary>
        internal static string msg_loading {
            get {
                return ResourceManager.GetString("msg_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessun Risultato.
        /// </summary>
        internal static string msg_search_not_result_found {
            get {
                return ResourceManager.GetString("msg_search_not_result_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerca.
        /// </summary>
        internal static string placeholder_search {
            get {
                return ResourceManager.GetString("placeholder_search", resourceCulture);
            }
        }
    }
}
